-- plugins/cmp/kind_icons.lua

local kind_icons = {
  Class = 'ﴯ',
  Color = '',
  Constant = '',
  Constructor = '',
  Enum = '',
  EnumMember = '',
  Event = '',
  Field = '',
  File = '',
  Folder = '',
  Function = '',
  Interface = '',
  Keyword = '',
  Method = '',
  Module = '',
  Operator = '',
  Property = 'ﰠ',
  Reference = '',
  Snippet = '',
  Struct = '',
  Text = '',
  TypeParameter = '',
  Unit = '',
  Value = '',
  Variable = '',
}

-- local kind_icons = {
--   Class = "",
--   Color = "",
--   Constant = "",
--   Constructor = "",
--   Enum = "",
--   EnumMember = "",
--   Event = "",
--   Field = "ﰠ",
--   File = "",
--   Folder = "",
--   Function = "",
--   Interface = "",
--   Keyword = "",
--   Method = "m",
--   Module = "",
--   Operator = "",
--   Property = "",
--   Reference = "",
--   Snippet = "",
--   Struct = "פּ",
--   Text = "",
--   TypeParameter = "",
--   Unit = "",
--   Value = "",
--   Variable = "",
-- }

return kind_icons
